image: alpine-node:11.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - "node_modules/"
  - "**/node_modules/"

stages:
  - setup
  - build
  - deploy

install:
  stage: setup
  script:
    - yarn
    - yarn lint

build:
  stage: build
  script:
    - yarn build

start:
  stage: deploy
  script:
    - docker-compose up