image: node:11.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - "node_modules/"
  - "**/node_modules/"

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - yarn

lint:
  stage: test
  script:
    - yarn lint

build:
  stage: build
  script:
    - yarn build

start:
  stage: deploy
  script:
    - docker-compose up