image: node:11.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy


before_script:
  - yarn

lint:
  stage: build
  script:
    - yarn run lint

build:
  stage: build
  script:
    - yarn run build
start:
  stage: deploy
  script:
    - docker-compose up