image: node:11.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - yarn

build:
  stage: build
  script:
    - yarn run build

lint:
  stage: test
  script:
    - yarn run lint


start:
  stage: deploy
  script:
    - docker-compose up