version: '3'

services:
  api:
    build:
      context: ./
      args:
        SERVICE_NAME: api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - APP_SECRET=23423423423
      - MONGO_INSTANCE_URL=mongodb://db:27017
      - M_ACCOUNT_USER=geoarchy
      - M_ACCOUNT_PASS=geoarchy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 45s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./
      args:
        SERVICE_NAME: web
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - APOLLO_SERVER_URL=http://api:8080
      - APOLLO_BROWSER_URL=http://localhost:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 45s
      timeout: 10s
      retries: 3

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db #Helps to store MongoDB data in `./mongo/data`
      - ./scripts/init-db.js:/docker-entrypoint-initdb.d/init-db.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=geoarchy
      - MONGO_INITDB_ROOT_PASSWORD=geoarchy


volumes:
  npm-cache:
    external: false
  mongo: